//
//  ChatMessage.swift
//  CH4_AI_Banking_app
//
//  Created by I Gusti Ngurah Bagus Ferry Mahayudha on 02/07/26.
//

import Foundation
import SwiftData

@Model
final class ChatMessage {
    @Attribute(.unique) var id: UUID
    var text: String
    var isUser: Bool // true if sent by user, false if generated by AI
    var timestamp: Date
    var conversationID: UUID? // Which Conversation this line belongs to (nil = legacy/unscoped)
    var citedDocumentIDs: [String] // LocalDocument ids this reply cited, so cards can be rebuilt on reload

    init(text: String, isUser: Bool, conversationID: UUID? = nil, citedDocumentIDs: [String] = []) {
        self.id = UUID()
        self.text = text
        self.isUser = isUser
        self.timestamp = Date()
        self.conversationID = conversationID
        self.citedDocumentIDs = citedDocumentIDs
    }
}
